[package]
name = "izi-noir"
version = "0.1.0"
description = "Privacy-preserving Solana program using Noir proofs"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "izi_noir"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.30.0"
